from graphviz import Digraph

dot = Digraph(comment='Flujo de Usuario')
dot.node('A', 'Inicio')
dot.node('B1', 'Selección de datos, con ID de Vizier')
dot.node('B2', 'Selección de datos, con Archivo CSV')
dot.node('B3', 'Selección de datos, con Archivo Excel')
dot.node('C', 'Selección de la tabla necesaria')
dot.node('D', 'Selección del metodo a usar')
dot.node('E', 'Completado de los inputs necesarios')
dot.node('F', '¿Se esta satisfecho con los resultados?')
dot.node('G', 'Aprobado, continuar con la interpretación')

dot.edge('A', 'B1')
dot.edge('A', 'B2')
dot.edge('A', 'B3')
dot.edge('B1', 'C')
dot.edge('B2', 'D')
dot.edge('B3', 'C')
dot.edges(['CD', 'DE', 'EF'])
dot.edge('F', 'G', label='Sí')
dot.edge('F', 'D', label='No')
dot.render('../Fig/user_diagram', format='png', view=True)
